### ISSUE TITLE
Error while copying files from repository

### ISSUE THREAD

**Issue by rokeno** [sevaa/tfvcget#2]
While using the task to copy files and folders on the deployment agent, we get: 
`2019-04-04T11:55:11.0355641Z ##[error]Microsoft.PowerShell.Commands.WriteErrorException: The specified wildcard character pattern is not valid: june_development_v1_v1_1[8W9QSS
2019-04-04T11:55:11.0566427Z ##[error]PowerShell script completed with 1 errors.
2019-04-04T11:55:11.0572598Z ##[section]Finishing: Get $/PROJECT/Sources/Development into DefaultWorkingDirectory
`
The current directory that was being copied has 2 files and 2 folders inside:
![image](https://user-images.githubusercontent.com/10266176/55554568-c55cb000-56eb-11e9-9eda-bd9fdddbeffc.png)

It appears that it doesn't like the open [ in the name of the folder.

**Comment by sevaa** [comment]
I presume, `june_development_v1_v1_1[8W9QSS` is a folder somewhere in the source tree?

**Comment by sevaa** [comment]
Here's a similar issue: https://github.com/psake/psake/issues/116

Looks like Test-Path treats [] as wildcard characters. I couldn't reproduce that on my system, maybe they've fixed Test-Path since 2014.

That said, I'll go ahead and get rid of Test-Path.

**Comment by sevaa** [comment]
Fixed (or so I think), published. Please refresh the extension and try again.

**Comment by rokeno** [comment]
Yes, it is.

**Comment by rokeno** [comment]
I will give it a shot when I get to a computer.

**Comment by rokeno** [comment]
Hey, i can confirm that this was solved. Thanks for the fast response and resolution!

**Comment by sevaa** [comment]
A positive review on VS Marketplace is how we say thanks :)

**Comment by rokeno** [comment]
You got it just now!
