### ISSUE TITLE
Use of Task Variable

### ISSUE THREAD

**Issue by GregB-Roberts** [sevaa/tfvcget#6]
I was hoping this app would allow the branch to be specified in a variable (as the default Get Sources) does not seem to support use of a variables. It expects everything to be hard coded? 
We have the same build definition which is valid across branches in a project. Being able to specifiy the branch means we dont need to duplicate the build definitions.
Having tried on tfvcget i get errors, e.g.
$/$(Project)/$(Branch)/Build
Microsoft.PowerShell.Commands.WriteErrorException: Exception calling "GetResult" with "0" argument(s): "TF10122: The path '$/$(Project)/$(Branch)/Build' contains a '$' at the beginning of a path component. Remove the '$' and try again."
So is it correct, your app does not support variables ?

Thanks

**Comment by sevaa** [comment]
Weird, but I'll take a look. I thought variable substitution happens within TFS itself, the tasks don't have to bother. Maybe this has to do with the $ in front...

**Comment by sevaa** [comment]
I'm having trouble reproducing this. I've created a TFVC Get step with source control path set to `$/$(Project)/$(Branch)/Process`, I've made release scoped variables `Project` and `Branch` set to a valid first and second level folder in TFVC. **The task works as expected.** The log reflects that the variables were properly substituted before the step execution.

Can you please check, are the `Project` and `Branch` variables properly initialized in your pipeline? Any trailing/leading spaces, maybe? Are they release scoped or stage scoped (if the latter, is that the right stage)? Is it on-prem TFS (AKA Azure DevOps Server) or the cloud Azure DevOps Services (formerly known as VSTS)?

**Comment by GregB-Roberts** [comment]
Thanks Seva

If you have it working then I suggest don’t spend anymore time. I found the problem.
I am using ADO Server 2019 1.1 (on premise)

It was the leading `$ I experimented with because in powershell it makes the char as just a char, no special meaning.

Apologies for wasting your time.

Thanks greg

========== info before ===========

BUILD_REPOSITORY_LOCALPATH=F:\tfsbuild\agent\_work\1\s

Error reported

Get `$/SCADA_Gecko/Development/Build into $(Build.Repository.LocalPath)/Build
·
2 errors
6s
Microsoft.PowerShell.Commands.WriteErrorException: Exception calling "GetResult" with "0" argument(s): "TF10125: The path '`$/SCADA_Gecko/Development/Build' must start with $/"
PowerShell script completed with 1 errors.

[cid:image002.png@01D5F923.2BF29F30]

[cid:image003.png@01D5F923.2BF29F30]

**Comment by sevaa** [comment]
No prob. I'll close the issue if it was on your side.
