### ISSUE TITLE
Not working on MAC Build Machines

### ISSUE THREAD

**Issue by jensheidrich-acn** [sevaa/tfvcget#8]
We are using:
- TFS 2018 Update 3.2
- Build Agent: v2.146.0 @ macOS Mojave (10.14.6)

Error Log:
##[error]File not found: '/Volumes/HDD2/Builds/A1/_tasks/TFVCGet_25bd5165-40a2-4ea9-80d6-e47b9ee4550e/2.0.0\TFVCGet.js'

**Comment by sevaa** [comment]
Confirmed. The file is there, but the backslash between 2.0.0 and TFVCGet.js throws it off.

**Comment by sevaa** [comment]
Fixed and published, please update and try again.

**Comment by jensheidrich-acn** [comment]
Great response time!
Need to uninstall and install again to get it to 2.0.1. Now it works.

Thanks

**Comment by sevaa** [comment]
In my experience, when an extension updates, it's enough to delete the task from the pipeline (AKA the definition) and then add it back. That'll refresh the version.

We say thanks by leaving a positive rating on the extension in the gallery. :)
