### ISSUE TITLE
FR: Possibility to download a TFVC item to a non existing folder

### ISSUE THREAD

**Issue by T0R3** [sevaa/tfvcget#9]
While using this extension I found a missing feature:
It would be great if a TFVC item could be downloaded to a non existing folder.

I think the magic happens here:
https://github.com/sevaa/tfvcget/blob/2ec121c09934183559ce1083917755dc1f1abe88/src/TFVCGet/TFVCGet.ps1#L91

I have the following use cases:
1. Download file to a non-existing folder
Download TFVC item (e.g. $/TeamProject/AFolder/AFile.WithExtension) to the target path (e.g. $(System.DefaultWorkingDirectory)/BFolder/AFile.WithExtension)

2. Download file to a non-existing folder and rename
Download TFVC item (e.g. $/TeamProject/AFolder/AFile.WithExtension) to the target path (e.g. $(System.DefaultWorkingDirectory)/BFolder/AFileRenamed.WithExtension)

**Comment by sevaa** [comment]
There are obvious workarounds for both use cases (i. e. create the folder first, do a rename command after). Is it that urgent to have all this functionality in one step? It will require, for one thing, new parameters.

**Comment by T0R3** [comment]
I think the rename is already implemented and you only have to create the folder first.

Your extension works great if i create the folder first and execute both use cases after. I dont think that it will require a new parameter.

**Comment by sevaa** [comment]
Imagine the situation: the source is a file called `foo.txt`, the destination is `c:\a\b`, where `c:\a` is a directory and `b` doesn't exist. Should the script assume that `foo.txt` should be downloaded as `c\a\b`, or that a folder called `b` should be created under `c:\a` and then `foo.txt` should be downloaded there?

The presence of an extension is not an indicator. Directory names can have extensions, too, and files can have no extension.

**Comment by T0R3** [comment]
Okay, now i understand what you mean!

I would expect that slashes are path separators and that every trailing slash will indicate that it is a folder and if not it will be a file and each parent folder has to be created . That should work for all your mentioned cases or?

**Comment by sevaa** [comment]
Trailing backslash makes sense. That I can do.

**Comment by sevaa** [comment]
I've implemented the check for the trailing backslash in a nonexistent target. Please update and check.

**Comment by sevaa** [comment]
No comment, closing.
